In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('titanic.csv')

In [5]:
df

,Unnamed: 0,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [7]:
df.shape

(418, 12)

In [16]:
df.sample(5)
# 5 random rows nikal ke do

,Unnamed: 0,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
14,14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
134,134,1026,3,"Dintcheff, Mr. Valtcho",male,43.0,0,0,349226,7.8958,NaN,S
324,324,1216,1,"Kreuchen, Miss. Emilie",female,39.0,0,0,24160,211.3375,NaN,S
130,130,1022,3,"Spinner, Mr. Henry John",male,32.0,0,0,STON/OQ. 369943,8.0500,NaN,S
2,2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   418 non-null    int64
 1   PassengerId  418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [19]:
#kya aap ke data pe missing values hai
df.isnull().sum()

Unnamed: 0       0
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [20]:
df.describe()

,Unnamed: 0,PassengerId,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,208.500000,1100.500000,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,120.810458,0.841838,14.181209,0.896760,0.981429,55.907576
min,0.000000,892.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,104.250000,996.250000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,208.500000,1100.500000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,312.750000,1204.750000,3.000000,39.000000,1.000000,0.000000,31.500000
max,417.000000,1309.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [14]:
#are there duplicates values
df.duplicated().sample(60)

155    False
193    False
302    False
208    False
27     False
371    False
65     False
332    False
52     False
367    False
112    False
158    False
304    False
156    False
185    False
100    False
49     False
164    False
253    False
42     False
238    False
215    False
190    False
73     False
122    False
241    False
41     False
321    False
118    False
43     False
399    False
274    False
409    False
392    False
25     False
182    False
12     False
340    False
376    False
33     False
16     False
161    False
15     False
0      False
133    False
379    False
387    False
366    False
128    False
18     False
132    False
363    False
64     False
388    False
34     False
102    False
135    False
300    False
92     False
291    False
dtype: bool